pin "pgbouncerhero/application", to: "pgbouncerhero/application.js"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from PgBouncerHero::Engine.root.join("app/javascript/pgbouncerhero/controllers"), under: "pgbouncerhero/controllers"
